### ISSUE TITLE
(node:173719) UnhandledPromiseRejectionWarning: Error: First argument of has method of Collection must be string.

### ISSUE THREAD

**Issue by thevagus** [ruhsjs/ruhs#13]
```
(node:173719) UnhandledPromiseRejectionWarning: Error: First argument of has method of Collection must be string.
    at Object.Collection.base.has (/home/vagus-linux/Software/JavaScript/ruhs-examples/node_modules/ruhs/src/utils/Collection.js:7:13)
    at Object.Collection.base.get (/home/vagus-linux/Software/JavaScript/ruhs-examples/node_modules/ruhs/src/utils/Collection.js:14:18)
    at createPresence (/home/vagus-linux/Software/JavaScript/ruhs-examples/node_modules/ruhs/src/structures/createPresence.js:20:34)
    at /home/vagus-linux/Software/JavaScript/ruhs-examples/node_modules/ruhs/src/structures/createGuild.js:106:22
    at Array.forEach (<anonymous>)
    at createGuild (/home/vagus-linux/Software/JavaScript/ruhs-examples/node_modules/ruhs/src/structures/createGuild.js:105:23)
    at WebSocket.<anonymous> (/home/vagus-linux/Software/JavaScript/ruhs-examples/node_modules/ruhs/src/methods/createSocket.js:159:31)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/home/vagus-linux/Software/JavaScript/ruhs-examples/node_modules/ws/lib/websocket.js:797:20)
    at Receiver.emit (events.js:315:20)
```

Node.js Version: v12.18.3
Ruhs Version: ultra-mega latest :smile:

**Comment by acarnd03** [comment]
I fixed in [last commit](https://github.com/ruhsjs/ruhs/commit/1ac2eba8fba61f7b2c4299318fc1b7dc183a49a1#diff-fc85c7ce25dec487a9205fc6c60f22f2L225), in [line 225](https://github.com/ruhsjs/ruhs/commit/1ac2eba8fba61f7b2c4299318fc1b7dc183a49a1#diff-fc85c7ce25dec487a9205fc6c60f22f2L225) i set channel instead of guild so ruhs can't find `members` property in channel structure.

This error occured when sending messages but channelCreate event must be emitted before.

I am not sure for this subject so i hold on.
